version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # username: admin & password: admin
     
  microservicemapinfo:
    image: microservicemapinfo:dev
    ports:
      - 80:80
      - 7020:7020

volumes:
  prometheus-data:
  grafana-data:

# reload prometheus without restarting:
# curl -X POST http://localhost:9090/-/reload
